#!/bin/bash

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 <git branch_ms> <docker tag>"
  exit 1
fi

dependecies_properties_path=../src/main/resources/dependencies.properties
common_pattern="common.git\="

branch_ms=$1
tag=$2
branch_common=$(grep $common_pattern $dependecies_properties_path | awk '{split($0,a,"$common_pattern"); print a[2]}')

sudo docker build --build-arg BRANCH_MS=$branch_ms --build-arg \
 --build-arg BRANCH_COMMON=$branch_common --no-cache -t fogbow/membership-service:$tag .

